/**
 * Development mode handler (serve)
 * Implements JIT route generation via virtual module
 */

import type { PluginHookHandler } from "../commons/types.js";
import type { ResolvedConfig, ViteDevServer, HmrContext } from "vite";
import { parseAppRouter, generateDevRoutesCode, generateEmptyRoutesCode, type PluginOptions } from "../commons/index.js";
import * as path from "path";
import * as fs from "fs";

const VIRTUAL_MODULE_ID = "virtual:app-router";
const RESOLVED_VIRTUAL_MODULE_ID = "\0" + VIRTUAL_MODULE_ID + ".js";

interface ServerContext {
    config?: ResolvedConfig;
    server?: ViteDevServer;
    options: PluginOptions;
    cachedCode?: string;
    appDir?: string;
}

const ctx: ServerContext = {
    options: {},
};

/**
 * Sets plugin options
 */
export function setOptions(options: PluginOptions): void {
    ctx.options = options;
}

/**
 * Outputs debug information based on debug option
 */
function outputDebug(code: string): void {
    const debug = ctx.options.debug;
    if (!debug) return;

    const separator = '='.repeat(60);
    const header = `\n${separator}\n[vite-plugin-react-app-router] Generated Routes (DEV)\n${separator}\n`;
    const footer = `\n${separator}\n`;

    if (debug === true || debug === 'console') {
        console.log(header + code + footer);
    } else if (typeof debug === 'string') {
        const outputPath = path.resolve(ctx.config?.root || process.cwd(), debug);
        fs.writeFileSync(outputPath, `// Generated by vite-plugin-react-app-router (DEV mode)\n// ${new Date().toISOString()}\n\n${code}`);
        console.log(`[vite-plugin-react-app-router] Debug output written to: ${outputPath}`);
    }
}

/**
 * Regenerates the routes code
 */
function regenerateRoutes(): string {
    if (!ctx.config) {
        return generateEmptyRoutesCode();
    }

    const rootDir = ctx.config.root;
    // ctx.appDir is normally pre-set by configResolved; fall back here in case
    // the virtual module is loaded outside the standard plugin lifecycle.
    const appDir = ctx.appDir
        ?? (ctx.options.appDir
            ? (path.isAbsolute(ctx.options.appDir)
                ? ctx.options.appDir
                : path.resolve(rootDir, ctx.options.appDir))
            : path.join(rootDir, "src/app"));
    ctx.appDir = appDir;

    if (!fs.existsSync(appDir)) {
        console.warn(`[vite-plugin-react-app-router] App directory not found: ${appDir}`);
        return generateEmptyRoutesCode();
    }

    const parsed = parseAppRouter({
        ...ctx.options,
        appDir,
    });

    // Use lazy loading by default for code splitting (can be disabled via options)
    const lazy = ctx.options.lazy !== false;
    ctx.cachedCode = generateDevRoutesCode(parsed.routes, {
        rootDir,
        lazy,
        rootNotFound: parsed.rootNotFound,
        intercepts: parsed.intercepts,
        tree: parsed.tree,
        rootLayout: parsed.rootLayout,
        rootPage: parsed.rootPage,
        rootError: parsed.rootError,
        rootLoading: parsed.rootLoading,
        rootSlots: parsed.rootSlots,
    });
    outputDebug(ctx.cachedCode);
    return ctx.cachedCode;
}

/**
 * Checks if a file (or directory) lives inside the app directory.
 */
function isAppPath(filePath: string): boolean {
    if (!ctx.appDir) return false;
    const normalizedPath = path.normalize(filePath);
    const normalizedAppDir = path.normalize(ctx.appDir);
    return normalizedPath === normalizedAppDir
        || normalizedPath.startsWith(normalizedAppDir + path.sep);
}

/**
 * Checks if it's a route-relevant file (page, layout, loading, error,
 * not-found, default).
 */
function isRouteFile(filePath: string): boolean {
    const basename = path.basename(filePath);
    const routeFiles = ["page", "layout", "loading", "error", "not-found", "default"];
    return routeFiles.some(rf => basename.startsWith(rf));
}

/**
 * Invalidates the cached virtual module and asks the dev client to do a full
 * reload. Safe to call repeatedly — Vite coalesces concurrent reloads.
 */
function triggerReload(server: ViteDevServer): void {
    ctx.cachedCode = undefined;
    const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_MODULE_ID);
    if (mod) {
        server.moduleGraph.invalidateModule(mod);
    }
    server.ws.send({ type: "full-reload", path: "*" });
}

const serverHandler: PluginHookHandler = {
    configResolved(config: ResolvedConfig) {
        ctx.config = config;
        // Resolve appDir eagerly so the watcher hooks below can match paths
        // even before the virtual module has been requested for the first time.
        ctx.appDir = ctx.options.appDir
            ? path.isAbsolute(ctx.options.appDir)
                ? ctx.options.appDir
                : path.resolve(config.root, ctx.options.appDir)
            : path.join(config.root, "src/app");
    },

    configureServer(server: ViteDevServer) {
        ctx.server = server;

        // handleHotUpdate covers FILE MODIFICATIONS only. Directory operations
        // (creating, renaming, removing folders like `[+clientes]/`) and file
        // adds/unlinks are surfaced through the chokidar watcher events. We
        // listen for them here so that mistakes like creating `[+cliente]/`
        // and renaming it to `[+clientes]/` rebuild the virtual module without
        // a manual server restart.
        const onFileChange = (filePath: string) => {
            if (isAppPath(filePath) && isRouteFile(filePath)) {
                triggerReload(server);
            }
        };
        const onDirChange = (dirPath: string) => {
            if (isAppPath(dirPath)) {
                triggerReload(server);
            }
        };
        server.watcher.on('add', onFileChange);
        server.watcher.on('unlink', onFileChange);
        server.watcher.on('addDir', onDirChange);
        server.watcher.on('unlinkDir', onDirChange);

        // Add virtual module resolution
        return () => {
            // Middleware not needed, we use resolveId and load
        };
    },

    handleHotUpdate(hmrCtx: HmrContext) {
        const { file, server } = hmrCtx;

        // If a route file was modified, invalidate the virtual module
        if (isAppPath(file) && isRouteFile(file)) {
            triggerReload(server);
        }
    },
};

// Export functions for use in the main plugin
export function resolveId(id: string): string | undefined {
    if (id === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_MODULE_ID;
    }
    return undefined;
}

export function load(id: string): string | undefined {
    if (id === RESOLVED_VIRTUAL_MODULE_ID) {
        return regenerateRoutes();
    }
    return undefined;
}

export const VIRTUAL_ID = VIRTUAL_MODULE_ID;
export const RESOLVED_ID = RESOLVED_VIRTUAL_MODULE_ID;

export default serverHandler;