/**
 * Client entry point
 * 
 * This module is imported by the user in their main.tsx
 * to use the router generated by the plugin.
 * 
 * Usage:
 * ```tsx
 * import { AppRouter } from 'vite-plugin-react-app-router/client';
 * 
 * createRoot(document.getElementById('root')!).render(
 *   <StrictMode>
 *     <AppRouter />
 *   </StrictMode>
 * );
 * ```
 */

// Re-export from virtual module
export { AppRouter, router, routes, default } from 'virtual:app-router';
