/**
 * Runtime helpers for vite-plugin-react-app-router. These are imported by the
 * generated virtual module and re-exported (selectively) to user code via
 * `vite-plugin-react-app-router/client`.
 *
 * Currently exposes the parallel-routes ("slots") API:
 *   - <SlotProvider slots={...}> wraps a layout and registers the slot
 *     definitions for that segment.
 *   - useSlot(name) reads the closest registered definition and returns a
 *     <SlotRenderer/> element that runs useRoutes against the current location.
 */

import { createContext, useContext, createElement } from 'react';
import type { ReactElement, ReactNode } from 'react';
import { useRoutes } from 'react-router-dom';
import type { RouteObject } from 'react-router-dom';

export interface SlotDefinition {
    /** Route table for this slot. Matched independently against the URL. */
    routes: RouteObject[];
    /** Element rendered when no route in `routes` matches. */
    defaultElement?: ReactElement | null;
}

const SlotContext = createContext<Record<string, SlotDefinition>>({});

interface SlotRendererProps {
    definition: SlotDefinition;
}

/**
 * Internal: runs useRoutes against the slot's routes for the current location.
 * Falls back to `defaultElement` when nothing matches.
 */
function SlotRenderer(props: SlotRendererProps): ReactElement | null {
    const matched = useRoutes(props.definition.routes);
    if (matched !== null && matched !== undefined) return matched;
    return props.definition.defaultElement ?? null;
}

/**
 * Look up a parallel-route slot by name. Returns an element that renders the
 * slot, or `null` when no slot with that name is registered in the closest
 * SlotProvider chain.
 */
export function useSlot(name: string): ReactElement | null {
    const slots = useContext(SlotContext);
    const def = slots[name];
    if (!def) return null;
    return createElement(SlotRenderer, { definition: def });
}

export interface SlotProviderProps {
    /** Slot definitions registered at this segment. Closer providers win. */
    slots: Record<string, SlotDefinition>;
    children: ReactNode;
}

/**
 * Internal: registers slot definitions for descendants. The generated module
 * inserts one of these around each layout whose segment owns @-prefixed slot
 * directories.
 */
export function SlotProvider(props: SlotProviderProps): ReactElement {
    const parent = useContext(SlotContext);
    // Closer-provider-wins: same-named slot defined deeper overrides outer.
    const merged: Record<string, SlotDefinition> = { ...parent, ...props.slots };
    return createElement(SlotContext.Provider, { value: merged }, props.children);
}

// Shared route modules (`+name/` definitions invoked via `[+name]`/`(+name)`).

export interface SharedModuleInfo {
    /** Name of the shared module rendered at this position (without `+`). */
    name: string;
    /** Names of nested sub-shareds active at this invocation (after `[-name]/` overrides). */
    activeSubShareds: ReadonlyArray<string>;
}

const SharedModuleContext = createContext<SharedModuleInfo | null>(null);

/**
 * Read the closest enclosing shared-module invocation. Returns `null` when not
 * inside one. Components inside a shared module's tree use this to discover
 * which sub-shareds were implemented at the current invocation site (e.g. so
 * a layout can hide a "histórico" link when `[-historico]/` was applied).
 */
export function useSharedModule(): SharedModuleInfo | null {
    return useContext(SharedModuleContext);
}

/**
 * Sugar for `useSharedModule()?.activeSubShareds.includes(subName) ?? false`.
 */
export function useSharedSlot(subName: string): boolean {
    const info = useContext(SharedModuleContext);
    return info ? info.activeSubShareds.includes(subName) : false;
}

export interface SharedModuleProviderProps {
    info: SharedModuleInfo;
    children: ReactNode;
}

/**
 * Internal: wraps a grafted shared-module subtree so descendants can call
 * useSharedModule() / useSharedSlot(). Generated by the codegen at every
 * `[+name]`/`(+name)` invocation site.
 */
export function SharedModuleProvider(props: SharedModuleProviderProps): ReactElement {
    return createElement(
        SharedModuleContext.Provider,
        { value: props.info },
        props.children
    );
}

// ---------------------------------------------------------------------------
// Shared-module props (`props.tsx` at an invocation site).
// ---------------------------------------------------------------------------

/**
 * Default value for the props context. Empty so that components calling
 * useSharedProps() outside an invocation get an object (not crashing) and can
 * destructure with defaults.
 */
const SharedPropsContext = createContext<Record<string, unknown>>({});

/**
 * Read the merged props supplied by the closest enclosing invocation site
 * `props.tsx`. Returns the raw default-export of that module, merged with any
 * outer providers (closer wins). Generic so callers can type the returned
 * shape against the schema declared in the shared module.
 */
export function useSharedProps<T = Record<string, unknown>>(): T {
    return useContext(SharedPropsContext) as T;
}

export interface SharedPropsProviderProps {
    /** Values exported by `props.tsx` at this invocation site / drill-down. */
    props: Record<string, unknown>;
    children: ReactNode;
}

/**
 * Internal: provides the values exported by `props.tsx`. Merges with outer
 * providers so deeper drill-downs can override fewer values without losing
 * what an outer invocation already supplied.
 */
export function SharedPropsProvider(props: SharedPropsProviderProps): ReactElement {
    const parent = useContext(SharedPropsContext);
    const merged = { ...parent, ...props.props };
    return createElement(
        SharedPropsContext.Provider,
        { value: merged },
        props.children
    );
}
